### ISSUE TITLE
Broken due to URL change to cloud.alphaess.com

### ISSUE THREAD

**Issue by bmannz** [CharlesGillanders/alphaess#2]
Due to Alpha changing the URL to cloud.alphaess.com this is now broken.
I have successfully tested it after changing the URL to cloud.alphaess.com

**Comment by corvidus** [comment]
Based on bmannz comment, probably just a case of updating the BASEURL global on Line 12 in https://github.com/CharlesGillanders/alphaess/blob/main/alphaess/alphaess.py
Hope that helps :)

**Comment by matt-oneill** [comment]
> Based on bmannz comment, probably just a case of updating the BASEURL global on Line 12 in https://github.com/CharlesGillanders/alphaess/blob/main/alphaess/alphaess.py
> Hope that helps :)

bmannz already has a pr for this change

**Comment by CharlesGillanders** [comment]
Thanks - that change is included in the package - version has been bumped to 0.0.4
